spring.application.name=gestao-usuarios

# ===============================
# COORDENADAS DO BANCO DE DADOS
# ===============================
spring.datasource.url=jdbc:postgresql://localhost:5432/gestao_usuarios
spring.datasource.username=postgres
spring.datasource.password=12345

# ===============================
# OPERADORES DO HIBERNATE (JPA)
# ===============================
# Atualiza o esquema do banco automaticamente baseado nas entidades Java
spring.jpa.hibernate.ddl-auto=update
# Mostra o SQL gerado no console (excelente para debug e validacao visual)
spring.jpa.show-sql=true
# Define o dialeto exato para otimizar as queries no PostgreSQL
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
server.port=8081
